### ISSUE TITLE
Issue in gitlab group creation if name has been taken

### ISSUE THREAD

**Issue by rafleze** [20tab/20tab-standard-project#53]
If name is taken an error occured:

```Choose the gitlab group path slug [cdc]:    
Traceback (most recent call last):
  File "/Users/rafleze/.pyenv/versions/3.7.5/lib/python3.7/site-packages/gitlab/exceptions.py", line 279, in wrapped_f
    return f(*args, **kwargs)
  File "/Users/rafleze/.pyenv/versions/3.7.5/lib/python3.7/site-packages/gitlab/mixins.py", line 214, in create
    server_data = self.gitlab.http_post(path, post_data=data, files=files, **kwargs)
  File "/Users/rafleze/.pyenv/versions/3.7.5/lib/python3.7/site-packages/gitlab/__init__.py", line 687, in http_post
    **kwargs
  File "/Users/rafleze/.pyenv/versions/3.7.5/lib/python3.7/site-packages/gitlab/__init__.py", line 575, in http_request
    response_body=result.content,
gitlab.exceptions.GitlabHttpError: 400: Failed to save group {:path=>["has already been taken"]}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/folders/sp/pfp036z90_qc42jcjpmvnrp80000gn/T/tmpngh0pdwj.py", line 103, in <module>
    main_process.run()
  File "/var/folders/sp/pfp036z90_qc42jcjpmvnrp80000gn/T/tmpngh0pdwj.py", line 98, in run
    exec(Path("./scripts/python/gitlab_sync.py").read_text())
  File "<string>", line 152, in <module>
  File "<string>", line 142, in run
  File "<string>", line 52, in create_group
  File "/Users/rafleze/.pyenv/versions/3.7.5/lib/python3.7/site-packages/gitlab/exceptions.py", line 281, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabCreateError: 400: Failed to save group {:path=>["has already been taken"]}
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)```

**Comment by niccolomineo** [comment]
@filippo-20tab, is this still happening? I reckon it is not.
